apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Postgres
    orgId: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://prometheus:9090
  basicAuth: false
  isDefault: true
  editable: true
- name: Postgres
  type: postgres
  access: proxy
  url: http://postgres:5432
  password: postgrespw
  user: postgres
  database: observatory
  basicAuth: false
  isDefault: false
  editable: true
